/**
 * This file is generated by the script in fetch_entity_structure and shouldn't be edited by hand
 *
 * Contains the names of all ICAT entities icat-admin can be used to access, and a map of their attributes and related entity types
 */

 /* eslint quote-props: 0 */

export const entityNames = ["Affiliation", "Application", "DataCollection", "DataCollectionDatafile", "DataCollectionDataset", "DataCollectionInvestigation", "DataCollectionParameter", "DataPublication", "DataPublicationDate", "DataPublicationFunding", "DataPublicationType", "DataPublicationUser", "Datafile", "DatafileFormat", "DatafileParameter", "Dataset", "DatasetInstrument", "DatasetParameter", "DatasetTechnique", "DatasetType", "Facility", "FacilityCycle", "FundingReference", "Grouping", "Instrument", "InstrumentScientist", "Investigation", "InvestigationFacilityCycle", "InvestigationFunding", "InvestigationGroup", "InvestigationInstrument", "InvestigationParameter", "InvestigationType", "InvestigationUser", "Job", "Keyword", "ParameterType", "PermissibleStringValue", "PublicStep", "Publication", "RelatedDatafile", "RelatedItem", "Rule", "Sample", "SampleParameter", "SampleType", "Shift", "Study", "StudyInvestigation", "Technique", "User", "UserGroup"] as const;
export type IcatEntityName = typeof entityNames[number];

type RelatedEntityField = { name: string; type: IcatEntityName; }
// Entities have three types of fields:
// 'attributes' are scalar values
// 'manys' and 'ones' are related entities with a one-many and X-one relationship, respectively
type EntityStructure = { "ones": RelatedEntityField[]; "manys": RelatedEntityField[]; "attributes": string[] }
type EntityStructureMap = Record<IcatEntityName, EntityStructure>

export const entityStructures: EntityStructureMap = {
    "Affiliation": {
        "attributes": [
            "createId",
            "createTime",
            "fullReference",
            "id",
            "modId",
            "modTime",
            "name",
            "pid"
        ],
        "manys": [],
        "ones": [
            {
                "name": "user",
                "type": "DataPublicationUser"
            }
        ]
    },
    "Application": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime",
            "name",
            "version"
        ],
        "manys": [
            {
                "name": "jobs",
                "type": "Job"
            }
        ],
        "ones": [
            {
                "name": "facility",
                "type": "Facility"
            }
        ]
    },
    "DataCollection": {
        "attributes": [
            "createId",
            "createTime",
            "doi",
            "id",
            "modId",
            "modTime"
        ],
        "manys": [
            {
                "name": "dataCollectionDatafiles",
                "type": "DataCollectionDatafile"
            },
            {
                "name": "dataCollectionDatasets",
                "type": "DataCollectionDataset"
            },
            {
                "name": "dataCollectionInvestigations",
                "type": "DataCollectionInvestigation"
            },
            {
                "name": "dataPublications",
                "type": "DataPublication"
            },
            {
                "name": "jobsAsInput",
                "type": "Job"
            },
            {
                "name": "jobsAsOutput",
                "type": "Job"
            },
            {
                "name": "parameters",
                "type": "DataCollectionParameter"
            }
        ],
        "ones": []
    },
    "DataCollectionDatafile": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime"
        ],
        "manys": [],
        "ones": [
            {
                "name": "dataCollection",
                "type": "DataCollection"
            },
            {
                "name": "datafile",
                "type": "Datafile"
            }
        ]
    },
    "DataCollectionDataset": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime"
        ],
        "manys": [],
        "ones": [
            {
                "name": "dataCollection",
                "type": "DataCollection"
            },
            {
                "name": "dataset",
                "type": "Dataset"
            }
        ]
    },
    "DataCollectionInvestigation": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime"
        ],
        "manys": [],
        "ones": [
            {
                "name": "dataCollection",
                "type": "DataCollection"
            },
            {
                "name": "investigation",
                "type": "Investigation"
            }
        ]
    },
    "DataCollectionParameter": {
        "attributes": [
            "createId",
            "createTime",
            "dateTimeValue",
            "error",
            "id",
            "modId",
            "modTime",
            "numericValue",
            "rangeBottom",
            "rangeTop",
            "stringValue"
        ],
        "manys": [],
        "ones": [
            {
                "name": "dataCollection",
                "type": "DataCollection"
            },
            {
                "name": "type",
                "type": "ParameterType"
            }
        ]
    },
    "DataPublication": {
        "attributes": [
            "createId",
            "createTime",
            "description",
            "id",
            "modId",
            "modTime",
            "pid",
            "publicationDate",
            "subject",
            "title"
        ],
        "manys": [
            {
                "name": "dates",
                "type": "DataPublicationDate"
            },
            {
                "name": "fundingReferences",
                "type": "DataPublicationFunding"
            },
            {
                "name": "relatedItems",
                "type": "RelatedItem"
            },
            {
                "name": "users",
                "type": "DataPublicationUser"
            }
        ],
        "ones": [
            {
                "name": "content",
                "type": "DataCollection"
            },
            {
                "name": "facility",
                "type": "Facility"
            },
            {
                "name": "type",
                "type": "DataPublicationType"
            }
        ]
    },
    "DataPublicationDate": {
        "attributes": [
            "createId",
            "createTime",
            "date",
            "dateType",
            "id",
            "modId",
            "modTime"
        ],
        "manys": [],
        "ones": [
            {
                "name": "publication",
                "type": "DataPublication"
            }
        ]
    },
    "DataPublicationFunding": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime"
        ],
        "manys": [],
        "ones": [
            {
                "name": "dataPublication",
                "type": "DataPublication"
            },
            {
                "name": "funding",
                "type": "FundingReference"
            }
        ]
    },
    "DataPublicationType": {
        "attributes": [
            "createId",
            "createTime",
            "description",
            "id",
            "modId",
            "modTime",
            "name"
        ],
        "manys": [
            {
                "name": "dataPublications",
                "type": "DataPublication"
            }
        ],
        "ones": [
            {
                "name": "facility",
                "type": "Facility"
            }
        ]
    },
    "DataPublicationUser": {
        "attributes": [
            "contributorType",
            "createId",
            "createTime",
            "email",
            "familyName",
            "fullName",
            "givenName",
            "id",
            "modId",
            "modTime",
            "orderKey"
        ],
        "manys": [
            {
                "name": "affiliations",
                "type": "Affiliation"
            }
        ],
        "ones": [
            {
                "name": "publication",
                "type": "DataPublication"
            },
            {
                "name": "user",
                "type": "User"
            }
        ]
    },
    "Datafile": {
        "attributes": [
            "checksum",
            "createId",
            "createTime",
            "datafileCreateTime",
            "datafileModTime",
            "description",
            "doi",
            "fileSize",
            "id",
            "location",
            "modId",
            "modTime",
            "name"
        ],
        "manys": [
            {
                "name": "dataCollectionDatafiles",
                "type": "DataCollectionDatafile"
            },
            {
                "name": "destDatafiles",
                "type": "RelatedDatafile"
            },
            {
                "name": "parameters",
                "type": "DatafileParameter"
            },
            {
                "name": "sourceDatafiles",
                "type": "RelatedDatafile"
            }
        ],
        "ones": [
            {
                "name": "datafileFormat",
                "type": "DatafileFormat"
            },
            {
                "name": "dataset",
                "type": "Dataset"
            }
        ]
    },
    "DatafileFormat": {
        "attributes": [
            "createId",
            "createTime",
            "description",
            "id",
            "modId",
            "modTime",
            "name",
            "type",
            "version"
        ],
        "manys": [
            {
                "name": "datafiles",
                "type": "Datafile"
            }
        ],
        "ones": [
            {
                "name": "facility",
                "type": "Facility"
            }
        ]
    },
    "DatafileParameter": {
        "attributes": [
            "createId",
            "createTime",
            "dateTimeValue",
            "error",
            "id",
            "modId",
            "modTime",
            "numericValue",
            "rangeBottom",
            "rangeTop",
            "stringValue"
        ],
        "manys": [],
        "ones": [
            {
                "name": "datafile",
                "type": "Datafile"
            },
            {
                "name": "type",
                "type": "ParameterType"
            }
        ]
    },
    "Dataset": {
        "attributes": [
            "complete",
            "createId",
            "createTime",
            "description",
            "doi",
            "endDate",
            "fileCount",
            "fileSize",
            "id",
            "location",
            "modId",
            "modTime",
            "name",
            "startDate"
        ],
        "manys": [
            {
                "name": "dataCollectionDatasets",
                "type": "DataCollectionDataset"
            },
            {
                "name": "datafiles",
                "type": "Datafile"
            },
            {
                "name": "datasetInstruments",
                "type": "DatasetInstrument"
            },
            {
                "name": "datasetTechniques",
                "type": "DatasetTechnique"
            },
            {
                "name": "parameters",
                "type": "DatasetParameter"
            }
        ],
        "ones": [
            {
                "name": "investigation",
                "type": "Investigation"
            },
            {
                "name": "sample",
                "type": "Sample"
            },
            {
                "name": "type",
                "type": "DatasetType"
            }
        ]
    },
    "DatasetInstrument": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime"
        ],
        "manys": [],
        "ones": [
            {
                "name": "dataset",
                "type": "Dataset"
            },
            {
                "name": "instrument",
                "type": "Instrument"
            }
        ]
    },
    "DatasetParameter": {
        "attributes": [
            "createId",
            "createTime",
            "dateTimeValue",
            "error",
            "id",
            "modId",
            "modTime",
            "numericValue",
            "rangeBottom",
            "rangeTop",
            "stringValue"
        ],
        "manys": [],
        "ones": [
            {
                "name": "dataset",
                "type": "Dataset"
            },
            {
                "name": "type",
                "type": "ParameterType"
            }
        ]
    },
    "DatasetTechnique": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime"
        ],
        "manys": [],
        "ones": [
            {
                "name": "dataset",
                "type": "Dataset"
            },
            {
                "name": "technique",
                "type": "Technique"
            }
        ]
    },
    "DatasetType": {
        "attributes": [
            "createId",
            "createTime",
            "description",
            "id",
            "modId",
            "modTime",
            "name"
        ],
        "manys": [
            {
                "name": "datasets",
                "type": "Dataset"
            }
        ],
        "ones": [
            {
                "name": "facility",
                "type": "Facility"
            }
        ]
    },
    "Facility": {
        "attributes": [
            "createId",
            "createTime",
            "daysUntilRelease",
            "description",
            "fullName",
            "id",
            "modId",
            "modTime",
            "name",
            "url"
        ],
        "manys": [
            {
                "name": "applications",
                "type": "Application"
            },
            {
                "name": "dataPublicationTypes",
                "type": "DataPublicationType"
            },
            {
                "name": "dataPublications",
                "type": "DataPublication"
            },
            {
                "name": "datafileFormats",
                "type": "DatafileFormat"
            },
            {
                "name": "datasetTypes",
                "type": "DatasetType"
            },
            {
                "name": "facilityCycles",
                "type": "FacilityCycle"
            },
            {
                "name": "instruments",
                "type": "Instrument"
            },
            {
                "name": "investigationTypes",
                "type": "InvestigationType"
            },
            {
                "name": "investigations",
                "type": "Investigation"
            },
            {
                "name": "parameterTypes",
                "type": "ParameterType"
            },
            {
                "name": "sampleTypes",
                "type": "SampleType"
            }
        ],
        "ones": []
    },
    "FacilityCycle": {
        "attributes": [
            "createId",
            "createTime",
            "description",
            "endDate",
            "id",
            "modId",
            "modTime",
            "name",
            "startDate"
        ],
        "manys": [
            {
                "name": "investigationFacilityCycles",
                "type": "InvestigationFacilityCycle"
            }
        ],
        "ones": [
            {
                "name": "facility",
                "type": "Facility"
            }
        ]
    },
    "FundingReference": {
        "attributes": [
            "awardNumber",
            "awardTitle",
            "createId",
            "createTime",
            "funderIdentifier",
            "funderName",
            "id",
            "modId",
            "modTime"
        ],
        "manys": [
            {
                "name": "investigations",
                "type": "InvestigationFunding"
            },
            {
                "name": "publications",
                "type": "DataPublicationFunding"
            }
        ],
        "ones": []
    },
    "Grouping": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime",
            "name"
        ],
        "manys": [
            {
                "name": "investigationGroups",
                "type": "InvestigationGroup"
            },
            {
                "name": "rules",
                "type": "Rule"
            },
            {
                "name": "userGroups",
                "type": "UserGroup"
            }
        ],
        "ones": []
    },
    "Instrument": {
        "attributes": [
            "createId",
            "createTime",
            "description",
            "fullName",
            "id",
            "modId",
            "modTime",
            "name",
            "pid",
            "type",
            "url"
        ],
        "manys": [
            {
                "name": "datasetInstruments",
                "type": "DatasetInstrument"
            },
            {
                "name": "instrumentScientists",
                "type": "InstrumentScientist"
            },
            {
                "name": "investigationInstruments",
                "type": "InvestigationInstrument"
            },
            {
                "name": "shifts",
                "type": "Shift"
            }
        ],
        "ones": [
            {
                "name": "facility",
                "type": "Facility"
            }
        ]
    },
    "InstrumentScientist": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime"
        ],
        "manys": [],
        "ones": [
            {
                "name": "instrument",
                "type": "Instrument"
            },
            {
                "name": "user",
                "type": "User"
            }
        ]
    },
    "Investigation": {
        "attributes": [
            "createId",
            "createTime",
            "doi",
            "endDate",
            "fileCount",
            "fileSize",
            "id",
            "modId",
            "modTime",
            "name",
            "releaseDate",
            "startDate",
            "summary",
            "title",
            "visitId"
        ],
        "manys": [
            {
                "name": "dataCollectionInvestigations",
                "type": "DataCollectionInvestigation"
            },
            {
                "name": "datasets",
                "type": "Dataset"
            },
            {
                "name": "fundingReferences",
                "type": "InvestigationFunding"
            },
            {
                "name": "investigationFacilityCycles",
                "type": "InvestigationFacilityCycle"
            },
            {
                "name": "investigationGroups",
                "type": "InvestigationGroup"
            },
            {
                "name": "investigationInstruments",
                "type": "InvestigationInstrument"
            },
            {
                "name": "investigationUsers",
                "type": "InvestigationUser"
            },
            {
                "name": "keywords",
                "type": "Keyword"
            },
            {
                "name": "parameters",
                "type": "InvestigationParameter"
            },
            {
                "name": "publications",
                "type": "Publication"
            },
            {
                "name": "samples",
                "type": "Sample"
            },
            {
                "name": "shifts",
                "type": "Shift"
            },
            {
                "name": "studyInvestigations",
                "type": "StudyInvestigation"
            }
        ],
        "ones": [
            {
                "name": "facility",
                "type": "Facility"
            },
            {
                "name": "type",
                "type": "InvestigationType"
            }
        ]
    },
    "InvestigationFacilityCycle": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime"
        ],
        "manys": [],
        "ones": [
            {
                "name": "facilityCycle",
                "type": "FacilityCycle"
            },
            {
                "name": "investigation",
                "type": "Investigation"
            }
        ]
    },
    "InvestigationFunding": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime"
        ],
        "manys": [],
        "ones": [
            {
                "name": "funding",
                "type": "FundingReference"
            },
            {
                "name": "investigation",
                "type": "Investigation"
            }
        ]
    },
    "InvestigationGroup": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime",
            "role"
        ],
        "manys": [],
        "ones": [
            {
                "name": "grouping",
                "type": "Grouping"
            },
            {
                "name": "investigation",
                "type": "Investigation"
            }
        ]
    },
    "InvestigationInstrument": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime"
        ],
        "manys": [],
        "ones": [
            {
                "name": "instrument",
                "type": "Instrument"
            },
            {
                "name": "investigation",
                "type": "Investigation"
            }
        ]
    },
    "InvestigationParameter": {
        "attributes": [
            "createId",
            "createTime",
            "dateTimeValue",
            "error",
            "id",
            "modId",
            "modTime",
            "numericValue",
            "rangeBottom",
            "rangeTop",
            "stringValue"
        ],
        "manys": [],
        "ones": [
            {
                "name": "investigation",
                "type": "Investigation"
            },
            {
                "name": "type",
                "type": "ParameterType"
            }
        ]
    },
    "InvestigationType": {
        "attributes": [
            "createId",
            "createTime",
            "description",
            "id",
            "modId",
            "modTime",
            "name"
        ],
        "manys": [
            {
                "name": "investigations",
                "type": "Investigation"
            }
        ],
        "ones": [
            {
                "name": "facility",
                "type": "Facility"
            }
        ]
    },
    "InvestigationUser": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime",
            "role"
        ],
        "manys": [],
        "ones": [
            {
                "name": "investigation",
                "type": "Investigation"
            },
            {
                "name": "user",
                "type": "User"
            }
        ]
    },
    "Job": {
        "attributes": [
            "arguments",
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime"
        ],
        "manys": [],
        "ones": [
            {
                "name": "application",
                "type": "Application"
            },
            {
                "name": "inputDataCollection",
                "type": "DataCollection"
            },
            {
                "name": "outputDataCollection",
                "type": "DataCollection"
            }
        ]
    },
    "Keyword": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime",
            "name"
        ],
        "manys": [],
        "ones": [
            {
                "name": "investigation",
                "type": "Investigation"
            }
        ]
    },
    "ParameterType": {
        "attributes": [
            "applicableToDataCollection",
            "applicableToDatafile",
            "applicableToDataset",
            "applicableToInvestigation",
            "applicableToSample",
            "createId",
            "createTime",
            "description",
            "enforced",
            "id",
            "maximumNumericValue",
            "minimumNumericValue",
            "modId",
            "modTime",
            "name",
            "pid",
            "units",
            "unitsFullName",
            "valueType",
            "verified"
        ],
        "manys": [
            {
                "name": "dataCollectionParameters",
                "type": "DataCollectionParameter"
            },
            {
                "name": "datafileParameters",
                "type": "DatafileParameter"
            },
            {
                "name": "datasetParameters",
                "type": "DatasetParameter"
            },
            {
                "name": "investigationParameters",
                "type": "InvestigationParameter"
            },
            {
                "name": "permissibleStringValues",
                "type": "PermissibleStringValue"
            },
            {
                "name": "sampleParameters",
                "type": "SampleParameter"
            }
        ],
        "ones": [
            {
                "name": "facility",
                "type": "Facility"
            }
        ]
    },
    "PermissibleStringValue": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime",
            "value"
        ],
        "manys": [],
        "ones": [
            {
                "name": "type",
                "type": "ParameterType"
            }
        ]
    },
    "PublicStep": {
        "attributes": [
            "createId",
            "createTime",
            "field",
            "id",
            "modId",
            "modTime",
            "origin"
        ],
        "manys": [],
        "ones": []
    },
    "Publication": {
        "attributes": [
            "createId",
            "createTime",
            "doi",
            "fullReference",
            "id",
            "modId",
            "modTime",
            "repository",
            "repositoryId",
            "url"
        ],
        "manys": [],
        "ones": [
            {
                "name": "investigation",
                "type": "Investigation"
            }
        ]
    },
    "RelatedDatafile": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime",
            "relation"
        ],
        "manys": [],
        "ones": [
            {
                "name": "destDatafile",
                "type": "Datafile"
            },
            {
                "name": "sourceDatafile",
                "type": "Datafile"
            }
        ]
    },
    "RelatedItem": {
        "attributes": [
            "createId",
            "createTime",
            "fullReference",
            "id",
            "identifier",
            "modId",
            "modTime",
            "relatedItemType",
            "relationType",
            "title"
        ],
        "manys": [],
        "ones": [
            {
                "name": "publication",
                "type": "DataPublication"
            }
        ]
    },
    "Rule": {
        "attributes": [
            "createId",
            "createTime",
            "crudFlags",
            "id",
            "modId",
            "modTime",
            "what"
        ],
        "manys": [],
        "ones": [
            {
                "name": "grouping",
                "type": "Grouping"
            }
        ]
    },
    "Sample": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime",
            "name",
            "pid"
        ],
        "manys": [
            {
                "name": "datasets",
                "type": "Dataset"
            },
            {
                "name": "parameters",
                "type": "SampleParameter"
            }
        ],
        "ones": [
            {
                "name": "investigation",
                "type": "Investigation"
            },
            {
                "name": "type",
                "type": "SampleType"
            }
        ]
    },
    "SampleParameter": {
        "attributes": [
            "createId",
            "createTime",
            "dateTimeValue",
            "error",
            "id",
            "modId",
            "modTime",
            "numericValue",
            "rangeBottom",
            "rangeTop",
            "stringValue"
        ],
        "manys": [],
        "ones": [
            {
                "name": "sample",
                "type": "Sample"
            },
            {
                "name": "type",
                "type": "ParameterType"
            }
        ]
    },
    "SampleType": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime",
            "molecularFormula",
            "name",
            "safetyInformation"
        ],
        "manys": [
            {
                "name": "samples",
                "type": "Sample"
            }
        ],
        "ones": [
            {
                "name": "facility",
                "type": "Facility"
            }
        ]
    },
    "Shift": {
        "attributes": [
            "comment",
            "createId",
            "createTime",
            "endDate",
            "id",
            "modId",
            "modTime",
            "startDate"
        ],
        "manys": [],
        "ones": [
            {
                "name": "instrument",
                "type": "Instrument"
            },
            {
                "name": "investigation",
                "type": "Investigation"
            }
        ]
    },
    "Study": {
        "attributes": [
            "createId",
            "createTime",
            "description",
            "endDate",
            "id",
            "modId",
            "modTime",
            "name",
            "pid",
            "startDate",
            "status"
        ],
        "manys": [
            {
                "name": "studyInvestigations",
                "type": "StudyInvestigation"
            }
        ],
        "ones": [
            {
                "name": "user",
                "type": "User"
            }
        ]
    },
    "StudyInvestigation": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime"
        ],
        "manys": [],
        "ones": [
            {
                "name": "investigation",
                "type": "Investigation"
            },
            {
                "name": "study",
                "type": "Study"
            }
        ]
    },
    "Technique": {
        "attributes": [
            "createId",
            "createTime",
            "description",
            "id",
            "modId",
            "modTime",
            "name",
            "pid"
        ],
        "manys": [
            {
                "name": "datasetTechniques",
                "type": "DatasetTechnique"
            }
        ],
        "ones": []
    },
    "User": {
        "attributes": [
            "affiliation",
            "createId",
            "createTime",
            "email",
            "familyName",
            "fullName",
            "givenName",
            "id",
            "modId",
            "modTime",
            "name",
            "orcidId"
        ],
        "manys": [
            {
                "name": "dataPublicationUsers",
                "type": "DataPublicationUser"
            },
            {
                "name": "instrumentScientists",
                "type": "InstrumentScientist"
            },
            {
                "name": "investigationUsers",
                "type": "InvestigationUser"
            },
            {
                "name": "studies",
                "type": "Study"
            },
            {
                "name": "userGroups",
                "type": "UserGroup"
            }
        ],
        "ones": []
    },
    "UserGroup": {
        "attributes": [
            "createId",
            "createTime",
            "id",
            "modId",
            "modTime"
        ],
        "manys": [],
        "ones": [
            {
                "name": "grouping",
                "type": "Grouping"
            },
            {
                "name": "user",
                "type": "User"
            }
        ]
    }
}
